import Golf6 from "../images/cars-big/golf6.jpg";
import AudiA1 from "../images/cars-big/audia1.jpg";
import Toyota from "../images/cars-big/toyotacamry.jpg";
import Bmw320 from "../images/cars-big/bmw320.jpg";
import Benz from "../images/cars-big/benz.jpg";
import Passat from "../images/cars-big/passatcc.jpg";

export const CAR_DATA = [
  [
    {
      name: "VW Golf 6",
      price: "37",
      img: Golf6,
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Audi A1 S-Line",
      price: "45",
      img: AudiA1,
      model: "Audi",
      mark: "A1",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Toyota Camry",
      price: "30",
      img: Toyota,
      model: "Camry",
      mark: "Toyota",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  ],
  [
    {
      name: "BMW 320 ModernLine",
      price: "35",
      img: Bmw320,
      model: "320",
      mark: "BMW",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "Mercedes-Benz GLK",
      price: "50",
      img: Benz,
      model: "Benz GLK",
      mark: "Mercedes",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      name: "VW Passat CC",
      price: "25",
      img: Passat,
      model: "Passat CC",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Honda Civic",
      price: "28",
      img: "HondaCivic",
      model: "Civic",
      mark: "Honda",
      year: "2010",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Ford Mustang GT",
      price: "55",
      img: "Mustang",
      model: "Mustang GT",
      mark: "Ford",
      year: "2015",
      doors: "2",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Chevrolet Camaro",
      price: "40",
      img: "Camaro",
      model: "Camaro",
      mark: "Chevrolet",
      year: "2013",
      doors: "2",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Nissan Altima",
      price: "32",
      img: "Altima",
      model: "Altima",
      mark: "Nissan",
      year: "2014",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Tesla Model S",
      price: "80",
      img: "TeslaModelS",
      model: "Model S",
      mark: "Tesla",
      year: "2018",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Electric",
    },
  ],
  [
    {
      name: "Subaru Outback",
      price: "34",
      img: "SubaruOutback",
      model: "Outback",
      mark: "Subaru",
      year: "2016",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Jeep Wrangler",
      price: "38",
      img: "JeepWrangler",
      model: "Wrangler",
      mark: "Jeep",
      year: "2017",
      doors: "2",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Hyundai Sonata",
      price: "29",
      img: "HyundaiSonata",
      model: "Sonata",
      mark: "Hyundai",
      year: "2013",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Kia Sportage",
      price: "27",
      img: "KiaSportage",
      model: "Sportage",
      mark: "Kia",
      year: "2015",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Mazda CX-5",
      price: "31",
      img: "MazdaCX5",
      model: "CX-5",
      mark: "Mazda",
      year: "2014",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Ford Focus",
      price: "26",
      img: "FordFocus",
      model: "Focus",
      mark: "Ford",
      year: "2015",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Volvo XC90",
      price: "52",
      img: "VolvoXC90",
      model: "XC90",
      mark: "Volvo",
      year: "2019",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  ],
  [
    {
      name: "Acura MDX",
      price: "48",
      img: "AcuraMDX",
      model: "MDX",
      mark: "Acura",
      year: "2017",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Lexus RX 350",
      price: "55",
      img: "LexusRX350",
      model: "RX 350",
      mark: "Lexus",
      year: "2020",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
  [
    {
      name: "Infiniti Q50",
      price: "42",
      img: "InfinitiQ50",
      model: "Q50",
      mark: "Infiniti",
      year: "2018",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
      
];
